server:
  port: 8888

app:
  api-prefix: /api/v1

services:
  identity:
    url: ${IDENTITY_URL:http://localhost:8080}
  medicine:
    url: ${MEDICINE_URL:http://localhost:8081}
  prescription:
    url: ${PRESCRIPTION_URL:http://localhost:8082}
  email:
    url: ${EMAIL_URL:http://localhost:8083}
  user:
    url: ${USER_URL:http://localhost:8084}
  chat:
    url: ${CHAT_URL:http://localhost:8000}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: ${services.identity.url}
          predicates:
          - Path=${app.api-prefix}/identity/**
          filters:
          - StripPrefix=2
        - id: medicine_service
          uri: ${services.medicine.url}
          predicates:
            - Path=${app.api-prefix}/medicine/**
          filters:
            - StripPrefix=2
        - id: chat_service
          uri: ${services.chat.url}
          predicates:
            - Path=${app.api-prefix}/chat/**
          filters:
            - StripPrefix=2
